### ISSUE TITLE
Samples project should have CI enabled

### ISSUE THREAD

**Issue by eeverman** [eeverman/andhow-samples#5]
AndHow currently has continuous integration, but the samples project does not.  This task is to add CI to andhow-samples.

AndHow currently uses Travis for Linux CI and AppVeyor for Windows CI, the samples could use the same.  Also, the samples should be built on JDK 8, 9, 10 & 11.

**Comment by code4t2** [comment]
So, @eeverman is this just to run `mvn test`? Or do you have anything else in mind?

**Comment by code4t2** [comment]
Travis just seems to run `mvn cobertura:cobertura`. I can add a `.yml` to the root, add cobertura to the `pom.xml` and see what happens. 

I can see it when I log into Travis, can't see it from AppVeyor, though. I think you'll have to add me as a user/administrator or add me to your GitHub team.

**Comment by code4t2** [comment]
I've been looking at AppVeyor a bit more closely. Seems like we can use it to build for both Ubuntu as well as Windows. Do you think we should go ahead and try that out?

**Comment by code4t2** [comment]
Yeah, @eeverman I think we can add a badge to the samples project. I didn't know about Travis catering to Windows. I think I'll look at it further and update the pull request.
